### PR TITLE
Update version control settings

### PR DESCRIPTION
**Pull request by aornelas**
* Stop ignoring *.meta files
* Commit all meta files
* Set Asset Serialization Mode to "Force Text" on Unity Editor Settings for better version control

NOTE: this means that now after running the export script there will be a ton of meta file changes again; we're investigating how to address this separately (https://jira.twitter.biz/browse/ADF-3347) but in the mean time, you'll have to just ignore meta files while reviewing PRs :/

jira: ADF-3328

### CODE REVIEW

**Comment by sdolim** [comment]
Probably better to not commit the metas in subsequent builds -- just git checkout -- that Support directory with all the .h files.

**Comment by aornelas** [comment]
ok, ignoring *.pidb.meta again; didn't quite get your other comment... can you please elaborate?

**Comment by sdolim** [comment]
I just meant that after running build.sh, you can revert all the modified .meta files rather than committing them.  Makes the PR easier to review and/or revert.

**Comment by aornelas** [comment]
ah got it. thanks, @sdolim!

@rsatrasala, if you didn't make any changes to the sample scene, you can simply do `git checkout *.meta` before creating a PR for cleaner diffs. once we improve our build script to avoid so many *.meta changes, we'll revisit your build script!

**Pull request merged**
