### PR TITLE
Push Unity packages for Unity Ads 2.2.0.0 and OnebyAOL 6.7.0.0 (Android)

### PR DESCRIPTION
**Pull request by chauduyphanvu1**

### CODE REVIEW

**Comment by PoojaChirp** [comment]
LGTM. 

Note: Packages get updated for both Android and iOS at the same time.

**Comment by rsatrasala** [comment]
I see updates for other networks in the podspec files. Is that intensional? If not this is good to go

**Comment by chauduyphanvu1** [comment]
@rsatrasala Yep, the podspecs are updated because they are pulled from the main iOS mediation repository. They don't contribute to this particular Unity repo, so we should selectively discard them going forward.

**Comment by rsatrasala** [comment]
LGTM then

**Pull request merged**
